[buildpack]
id = "borealis/postgres-tunnel"
name = "Borealis Isolated Postgres Buildpack"
homepage = "https://github.com/OldSneerJaw/heroku-buildpack-borealis-pg-tunnel"

[publish]

[publish.Ignore]
files = [".gitignore"]
